quarkus:
  application:
    name: transaction-ms

  http:
    port: 8080
    host: 0.0.0.0

  jackson:
    write-dates-as-timestamps: false

cosmos:
  endpoint: ${COSMOS_ENDPOINT}
  key: ${COSMOS_KEY}
  database: Bank
  containers:
    transfers: Transfers
    purchases: Purchases
    cards: Cards
    accounts: Accounts
    exchangeRates: ExchangeRates

mp:
  jwt:
    verify:
      publickey: ${JWT_PUBLIC_KEY}
      issuer: banking-auth